name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cpp-linter/cpp-linter-action@v2
      with:
        style: 'LLVM'
        tidy-checks: '-*' # disable tidy check
        lines-changed-only: 'false'

    - name: Install dependency
      run: make deps

    - name: 1. Compile
      run: make build
    - name: 2. Run executable
      run: ./main
    - name: 3. Generate reports
      run: |
        make lcov-report
        make gcovr-report

    - name: Upload lcov and gcovr reports
      if: github.ref == 'refs/heads/main'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b coverage
        git add lcov-report/*
        git commit -m "Upload lcov report"
        git push -f origin coverage

