name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cpp-linter/cpp-linter-action@v2
      with:
        style: 'LLVM'
        tidy-checks: '-*' # disable tidy check
        lines-changed-only: 'false'

    - name: Install dependency
      run: make deps

    - name: 1. Compile
      run: make build
    - name: 2. Run executable
      run: ./main
    - name: 3. Generate reports
      run: |
        make lcov-report
        make gcovr-report
        
    - name: Create coverage badges
      run: |
        # Extract line and function coverage percentages (as shown in the previous step)

        line_coverage=$(grep -oP "(?<=lines......: )\d+\.\d+" lcov-report/lcov.info)
        function_coverage=$(grep -oP "(?<=functions..: )\d+\.\d+" lcov-report/lcov.info)

        # Generate badge URLs
        line_badge_url="https://img.shields.io/badge/Lines%20Coverage-$line_coverage%25-brightgreen"
        function_badge_url="https://img.shields.io/badge/Functions%20Coverage-$function_coverage%25-brightgreen"

        echo "Line coverage: $line_coverage"
        echo "Function coverage: $function_coverage"
        echo "Line coverage badge URL: $line_badge_url"
        echo "Function coverage badge URL: $function_badge_url"
    - name: Update README
      run: |
          # Extract line and function coverage percentages (as shown in the previous step)

          line_coverage=$(grep -oP "(?<=lines......: )\d+\.\d+" lcov-report/lcov.info)
          function_coverage=$(grep -oP "(?<=functions..: )\d+\.\d+" lcov-report/lcov.info)
          
          # Generate badge URLs
          line_badge_url="https://img.shields.io/badge/Lines%20Coverage-$line_coverage%25-brightgreen"
          function_badge_url="https://img.shields.io/badge/Functions%20Coverage-$function_coverage%25-brightgreen"
          
    # - name: Upload lcov and gcovr reports
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     git config user.name github-actions
    #     git config user.email github-actions@github.com
    #     git checkout -b coverage
    #     git add lcov-report/*
    #     git commit -m "Upload lcov report"
    #     git push -f origin coverage
    # Required for generating html artifact, can be skipped if not generating html artifact
    - uses: hrishikesh-kadam/setup-lcov@v1 

    - uses: kefasjw/lcov-pull-request-report@v1
      with:
        # Lcov file location. For example, coverage/lcov.info
        lcov-file: lcov-report/lcov.info

        # Github token required for getting list of changed files and posting comments
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
        # Working directory
        # Default: empty (repository root)
        working-directory:

        # Report comment title
        # Default: empty
        comment-title:

        # All files minimum coverage in percentage. For example, 0, 50, 100
        # Default: 0
        all-files-minimum-coverage:

        # Changed files minimum coverage in percentage. For example, 0, 50, 100
        # Default: 0
        changed-files-minimum-coverage:

        # Artifact name of the generated html. Requires LCOV to be installed
        # Default: empty (skip uploading artifact)
        artifact-name:

